### ISSUE TITLE
error with location.php [Class "config" does not exist]

### ISSUE THREAD

**Issue by maximuml** [xiaomlove/nexusphp#14]
```
2021/05/05 16:05:48 [error] 1042#0: *2551 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ReflectionException: Class "config" does not exist in /home/wwwroot/local.domain/vendor/laravel/framework/src/Illuminate/Container/Container.php:833
Stack trace:
#0 /home/wwwroot/local.domain/vendor/laravel/framework/src/Illuminate/Container/Container.php(833): ReflectionClass->__construct()
#1 /home/wwwroot/local.domain/vendor/laravel/framework/src/Illuminate/Container/Container.php(714): Illuminate\Container\Container->build()
#2 /home/wwwroot/local.domain/vendor/laravel/framework/src/Illuminate/Container/Container.php(652): Illuminate\Container\Container->resolve()
#3 /home/wwwroot/local.domain/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(119): Illuminate\Container\Container->make()
#4 /home/wwwroot/local.domain/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(275): app()
#5 /home/wwwroot/local.domain/public/location.php(9): config()
#6 {main}

Next Illuminate\Contracts\Container\BindingResolutionException: Target class [config] does not" while reading response header from upstream, client: 37.146.144.208, server: local.domain, request: "GET /location.php HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-cgi.sock:", host: "local.domain", referrer: "http://local.domain/staffpanel.php"
```

**Comment by xiaomlove** [comment]
do you run the upgrade program successfully?

**Comment by maximuml** [comment]
I run composer install and composer update
Any more commands I need to run?

**Comment by xiaomlove** [comment]
Sorry about the doc no English version now。
1, copy new code over write the olds
2, run composer install
3, copy nexus/Install/update/update.php to public/update/update.php，than open yourdonain/update/update.php，complete the upgrade steps.

**Comment by xiaomlove** [comment]
Also,checkout the documentation, add some configuration for the management system

**Comment by maximuml** [comment]
Just made reinstall and everythink allright! thanks

**Comment by maximuml** [comment]
but still got the same error with location.php

**Comment by maximuml** [comment]
```
2021/05/06 21:24:18 [error] 24795#0: *224 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ReflectionException: Class "config" does not exist in /home/wwwroot/***/vendor/laravel/framework/src/Illuminate/Container/Container.php:833
Stack trace:
#0 /home/wwwroot/***/vendor/laravel/framework/src/Illuminate/Container/Container.php(833): ReflectionClass->__construct()
#1 /home/wwwroot/***/vendor/laravel/framework/src/Illuminate/Container/Container.php(714): Illuminate\Container\Container->build()
#2 /home/wwwroot/***/vendor/laravel/framework/src/Illuminate/Container/Container.php(652): Illuminate\Container\Container->resolve()
#3 /home/wwwroot/***/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(119): Illuminate\Container\Container->make()
#4 /home/wwwroot/***/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(275): app()
#5 /home/wwwroot/***/public/location.php(9): config()
#6 {main}

Next Illuminate\Contracts\Container\BindingResolutionException: Target class [config] does not" while reading response header from upstream, client: 37.146.144.208, server: ***, request: "GET /location.php HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-cgi.sock:", host: "***", referrer: "http://***/staffpanel.php"
```

**Comment by xiaomlove** [comment]
you can fixed it [like this](https://github.com/xiaomlove/nexusphp/commit/3853b95adcde87c704b59708c39040b126113b78#diff-8e25501ba4e7d00db07dd622df49238517e13e5eae0f7a088b118e4fbaf0ad57L9) temporary.

**Comment by maximuml** [comment]
Thanks it's work! is it any way to detect user ip location through geoip2 db? thanks

**Comment by maximuml** [comment]
and seems like next error with attachment in news
```
2021/05/06 21:56:49 [error] 24795#0: *273 FastCGI sent in stderr: "Unable to open primary script: /home/wwwroot/***/public/attachments/202105/shoutbox.php (No such file or directory)" while reading response header from upstream, client: 37.146.144.208, server: ***, request: "GET /attachments/202105/shoutbox.php?type=shoutbox HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-cgi.sock:", host: "***", referrer: "http://***/attachments/202105/20210507025105564c9707adba28c8806bb6fba5daf588.jpg.thumb.jpg"
```

**Comment by xiaomlove** [comment]
request ` /attachments/202105/shoutbox.php?type=shoutbox` ? where does it happen ?

**Comment by maximuml** [comment]
Then i go to /attachments/202105/shoutbox.php?type=shoutbox i just got blank page - No input file specified

**Comment by xiaomlove** [comment]
Where will do that request？

**Comment by maximuml** [comment]
I just add news on index page with attached image

**Comment by maximuml** [comment]
![Screenshot_20210507-164425__01](https://user-images.githubusercontent.com/9083083/117459020-97459c00-af53-11eb-8a17-c2532504fba2.jpg)

**Comment by xiaomlove** [comment]
try this: 
```
ln -s <YOUR_CODE_ROOT_PATH>/attachments <YOUR_CODE_ROOT_PATH>/public
```
Under normal circumstances, the installer will complete this setup

**Comment by maximuml** [comment]
Yes. I already did it!!

**Comment by maximuml** [comment]
Thanks.
