### ISSUE TITLE
安装过程出错，无法创建数据表

### ISSUE THREAD

**Issue by HaodongZou** [xiaomlove/nexusphp#187]
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/38043100/235647552-f2546164-b5ed-4a25-acaa-8b2ded3660be.png">

在创建数据库表的时候显示ERROR:[]，没有任何的报错信息。Nginx的error.log和/tmp/nexus-2023-05-02.log均没有错误日志。

这时如果关闭页面便无法再打开，Nginx的error.log报错如下：
```log
2023/05/02 18:43:20 [error] 89152#0: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nexusphp.settings' doesn't exist in /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Database/Connection.php:414
Stack trace:
#0 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Database/Connection.php(414): PDO->prepare('select `name`, ...')
#1 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Database/Connection.php(753): Illuminate\Database\Connection->Illuminate\Database\{closure}('select `name`, ...', Array)
#2 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\Database\Connection->runQueryCallback('select `name`, ...', Array, Object(Closure))
#3 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Database/Connection.php(405): Illuminate\Database\Connection->run('select `name`, ...', Array, Object(Closure))
#4 /Users/zouhd/D" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "127.0.0.1:8080"
``` 

/tmp/nexus-2023-05-02.log报错如下：
```log
[2023-05-02 10:18:17] [794a6450e36922f1d7202248979c261f] production.ERROR: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nexusphp.settings' doesn't exist (SQL: select `name`, `value` from `settings` where `autoload` = yes) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nexusphp.settings' doesn't exist (SQL: select `name`, `value` from `settings` where `autoload` = yes) at /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Database/Connection.php:760)
[stacktrace]
#0 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\\Database\\Connection->runQueryCallback('select `name`, ...', Array, Object(Closure))
#1 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Database/Connection.php(405): Illuminate\\Database\\Connection->run('select `name`, ...', Array, Object(Closure))
#2 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2705): Illuminate\\Database\\Connection->select('select `name`, ...', Array, true)
#3 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2694): Illuminate\\Database\\Query\\Builder->runSelect()
#4 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3230): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#5 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2693): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))
#6 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(710): Illuminate\\Database\\Query\\Builder->get(Array)
#7 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(694): Illuminate\\Database\\Eloquent\\Builder->getModels(Array)
#8 /Users/zouhd/Development/nexusphp/app/Models/Setting.php(53): Illuminate\\Database\\Eloquent\\Builder->get(Array)
#9 /Users/zouhd/Development/nexusphp/include/globalfunctions.php(311): App\\Models\\Setting::getFromDb()
#10 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(397): {closure}()
#11 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(419): Illuminate\\Cache\\Repository->remember('nexus_settings_...', 600, Object(Closure))
#12 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(338): Illuminate\\Cache\\CacheManager->__call('remember', Array)
#13 /Users/zouhd/Development/nexusphp/nexus/Database/NexusDB.php(336): Illuminate\\Support\\Facades\\Facade::__callStatic('remember', Array)
#14 /Users/zouhd/Development/nexusphp/include/globalfunctions.php(309): Nexus\\Database\\NexusDB::remember('nexus_settings_...', 600, Object(Closure))
#15 /Users/zouhd/Development/nexusphp/routes/web.php(27): get_setting('security.login_...')
#16 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Routing/RouteFileRegistrar.php(35): require('/Users/zouhd/De...')
#17 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(503): Illuminate\\Routing\\RouteFileRegistrar->register('/Users/zouhd/De...')
#18 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(457): Illuminate\\Routing\\Router->loadRoutes('/Users/zouhd/De...')
#19 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Routing/RouteRegistrar.php(192): Illuminate\\Routing\\Router->group(Array, '/Users/zouhd/De...')
#20 /Users/zouhd/Development/nexusphp/app/Providers/RouteServiceProvider.php(48): Illuminate\\Routing\\RouteRegistrar->group('/Users/zouhd/De...')
#21 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Providers\\RouteServiceProvider->App\\Providers\\{closure}()
#22 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#23 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(81): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#24 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Object(Closure), Object(Closure))
#25 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Object(Closure), Array, NULL)
#26 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Foundation/Support/Providers/RouteServiceProvider.php(120): Illuminate\\Container\\Container->call(Object(Closure))
#27 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Foundation/Support/Providers/RouteServiceProvider.php(45): Illuminate\\Foundation\\Support\\Providers\\RouteServiceProvider->loadRoutes()
#28 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Foundation\\Support\\Providers\\RouteServiceProvider->Illuminate\\Foundation\\Support\\Providers\\{closure}()
#29 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#30 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(81): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#31 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Object(Closure), Object(Closure))
#32 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Object(Closure), Array, NULL)
#33 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php(119): Illuminate\\Container\\Container->call(Object(Closure))
#34 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(932): Illuminate\\Support\\ServiceProvider->callBootedCallbacks()
#35 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(910): Illuminate\\Foundation\\Application->bootProvider(Object(App\\Providers\\RouteServiceProvider))
#36 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(App\\Providers\\RouteServiceProvider), 40)
#37 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(909): array_walk(Array, Object(Closure))
#38 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#39 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(242): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#40 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#41 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(160): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#42 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#43 /Users/zouhd/Development/nexusphp/public/nexus.php(51): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#44 {main}

[previous exception] [object] (PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nexusphp.settings' doesn't exist at /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Database/Connection.php:414)
[stacktrace]
#0 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Database/Connection.php(414): PDO->prepare('select `name`, ...')
#1 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Database/Connection.php(753): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}('select `name`, ...', Array)
#2 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\\Database\\Connection->runQueryCallback('select `name`, ...', Array, Object(Closure))
#3 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Database/Connection.php(405): Illuminate\\Database\\Connection->run('select `name`, ...', Array, Object(Closure))
#4 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2705): Illuminate\\Database\\Connection->select('select `name`, ...', Array, true)
#5 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2694): Illuminate\\Database\\Query\\Builder->runSelect()
#6 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3230): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#7 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2693): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))
#8 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(710): Illuminate\\Database\\Query\\Builder->get(Array)
#9 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(694): Illuminate\\Database\\Eloquent\\Builder->getModels(Array)
#10 /Users/zouhd/Development/nexusphp/app/Models/Setting.php(53): Illuminate\\Database\\Eloquent\\Builder->get(Array)
#11 /Users/zouhd/Development/nexusphp/include/globalfunctions.php(311): App\\Models\\Setting::getFromDb()
#12 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(397): {closure}()
#13 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(419): Illuminate\\Cache\\Repository->remember('nexus_settings_...', 600, Object(Closure))
#14 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(338): Illuminate\\Cache\\CacheManager->__call('remember', Array)
#15 /Users/zouhd/Development/nexusphp/nexus/Database/NexusDB.php(336): Illuminate\\Support\\Facades\\Facade::__callStatic('remember', Array)
#16 /Users/zouhd/Development/nexusphp/include/globalfunctions.php(309): Nexus\\Database\\NexusDB::remember('nexus_settings_...', 600, Object(Closure))
#17 /Users/zouhd/Development/nexusphp/routes/web.php(27): get_setting('security.login_...')
#18 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Routing/RouteFileRegistrar.php(35): require('/Users/zouhd/De...')
#19 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(503): Illuminate\\Routing\\RouteFileRegistrar->register('/Users/zouhd/De...')
#20 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(457): Illuminate\\Routing\\Router->loadRoutes('/Users/zouhd/De...')
#21 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Routing/RouteRegistrar.php(192): Illuminate\\Routing\\Router->group(Array, '/Users/zouhd/De...')
#22 /Users/zouhd/Development/nexusphp/app/Providers/RouteServiceProvider.php(48): Illuminate\\Routing\\RouteRegistrar->group('/Users/zouhd/De...')
#23 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Providers\\RouteServiceProvider->App\\Providers\\{closure}()
#24 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#25 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(81): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#26 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Object(Closure), Object(Closure))
#27 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Object(Closure), Array, NULL)
#28 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Foundation/Support/Providers/RouteServiceProvider.php(120): Illuminate\\Container\\Container->call(Object(Closure))
#29 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Foundation/Support/Providers/RouteServiceProvider.php(45): Illuminate\\Foundation\\Support\\Providers\\RouteServiceProvider->loadRoutes()
#30 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Foundation\\Support\\Providers\\RouteServiceProvider->Illuminate\\Foundation\\Support\\Providers\\{closure}()
#31 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#32 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(81): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#33 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Object(Closure), Object(Closure))
#34 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Object(Closure), Array, NULL)
#35 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php(119): Illuminate\\Container\\Container->call(Object(Closure))
#36 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(932): Illuminate\\Support\\ServiceProvider->callBootedCallbacks()
#37 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(910): Illuminate\\Foundation\\Application->bootProvider(Object(App\\Providers\\RouteServiceProvider))
#38 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(App\\Providers\\RouteServiceProvider), 40)
#39 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(909): array_walk(Array, Object(Closure))
#40 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#41 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(242): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#42 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#43 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(160): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#44 /Users/zouhd/Development/nexusphp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#45 /Users/zouhd/Development/nexusphp/public/nexus.php(51): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#46 {main}
"} 
[2023-05-02 10:46:06] [d6ab6450e9ee7eb3985253041158a255] [0] [0.057] [0] [!IN_NEXUS:Target class [hash] does not exist.] production.debug /Users/zouhd/Development/nexusphp/nexus/Plugin/Hook.php:62 Nexus\Plugin\Hook->doAction No this hook: nexus_register
[2023-05-02 10:46:06] [d6ab6450e9ee7eb3985253041158a255] [1] [0.110] [0] [] production.debug /Users/zouhd/Development/nexusphp/nexus/Plugin/Hook.php:62 Nexus\Plugin\Hook->doAction No this hook: nexus_boot

```

环境：macOS Ventura 13.1 、PHP 8.2.5、mysql  Ver 8.0.28 for macos11 on arm64 (MySQL Community Server - GPL)、Redis server v=7.0.11

尝试了php8分支、v1.8.0都是一样的问题。

我遇到的问题应该与 #84 类似

**Comment by xiaomlove** [comment]
第2步创建了 .env 程序认为已经安装成功，所以不会进入安装程序。你可以尝试直接输入 `/install/install.php`

**Comment by xiaomlove** [comment]
错误的原因是什么？

**Comment by HaodongZou** [comment]
不清楚。。我手动打开`install.php`就可以正常创建tables了。
